### PR TITLE
Configuration Enhancements for MK3S+ with Revo-Hotend

### PR DESCRIPTION
**Pull request by chrisvgt**
Hello everyone! 🚀

I appreciate the great configuration, but while setting up my MK3S+ with the Revo-Hotend, I encountered and addressed a few issues:

1. **Z-Axis Calibration:**
   - Corrected z-axis calibration by adjusting steps from `210` to `215` in `steps.cfg`.
   - The z-axis calibration was not accurate due to a discrepancy in the number of steps, resulting in the axis not reaching its endpoints. This was caused by the `prusa.cfg` file overwriting the correct configuration in `steps.cfg`. I've adjusted the steps to ensure the z-axis aligns with the endpoints, mirroring the behavior in the Prusa firmware.
  
2. **Z-Offset Adjustment:**
   - Increased `horizontal_move` from `2` to `5` to prevent triggering errors during calibration with a higher `z_offset` then usual.
   - I use a slightly thinner steel plate, leading to a `z_offset` of `1.870`. While this offset worked seamlessly with the Prusa firmware, your configuration triggered an error during calibration: *"Probe triggered prior to movement klipper."* To fix this, I increased the `horizontal_move`, preventing the PINDA from being triggered excessively.

3. **Revo-Hotend Configuration:**
   - Added a dedicated configuration for the Revo hotend. Prusa now supports the hotend so it might be good to add the configuration.

Looking forward to your feedback!

Cheers,
chrisvgt

### CODE REVIEW

**Review by dz0ny — APPROVED** [review]

**Comment by dz0ny** [comment]
If I remember correctly **position_max** was set to handle Bondtech hot-end correctly.

**Comment by chrisvgt** [comment]
Wouldn't it be better to create an extra configuration file for this hotend? Otherwise the default hotend will not be calibrated correctly with the old setting.

**Comment by chrisvgt** [comment]
> If I remember correctly **position_max** was set to handle Bondtech hot-end correctly.

Wouldn't it be better to create an extra configuration file for this hotend? Otherwise the default hotend will not be calibrated correctly with the old setting.

**Comment by dz0ny** [comment]
> > If I remember correctly **position_max** was set to handle Bondtech hot-end correctly.
> 
> Wouldn't it be better to create an extra configuration file for this hotend? Otherwise the default hotend will not be calibrated correctly with the old setting.

Yep it was leftover, removed it.

**Pull request merged**
